import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Bakery OP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="h-screen" lang="en">
      <body className={inter.className}>
        <div className="flex flex-row">
          <Navbar />
          <div className = "pl-24">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
