import Link from "next/link";

export default function Home() {
  return (
    <>
      <div className="">
        <video
          className="h-full w-full object-cover"
          src="/cake.mp4"
          type="video/mp4"
          autoPlay
          muted
          loop
        ></video>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
        <h1 className="text-center">test</h1>
      </div>
    </>
  );
}
